// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BetterScroll: typeof import('./src/components/custom/BetterScroll.vue')['default']
    CountTo: typeof import('./src/components/custom/CountTo.vue')['default']
    DarkModeContainer: typeof import('./src/components/common/DarkModeContainer.vue')['default']
    DarkModeSwitch: typeof import('./src/components/common/DarkModeSwitch.vue')['default']
    HoverContainer: typeof import('./src/components/common/HoverContainer.vue')['default']
    IconCustomAvatar: typeof import('~icons/custom/avatar')['default']
    IconCustomBanner: typeof import('~icons/custom/banner')['default']
    IconGridiconsFullscreen: typeof import('~icons/gridicons/fullscreen')['default']
    IconGridiconsFullscreenExit: typeof import('~icons/gridicons/fullscreen-exit')['default']
    IconLineMdMenuFoldLeft: typeof import('~icons/line-md/menu-fold-left')['default']
    IconLineMdMenuUnfoldLeft: typeof import('~icons/line-md/menu-unfold-left')['default']
    IconMdiMoonWaningCrescent: typeof import('~icons/mdi/moon-waning-crescent')['default']
    IconMdiPin: typeof import('~icons/mdi/pin')['default']
    IconMdiPinOff: typeof import('~icons/mdi/pin-off')['default']
    IconMdiRefresh: typeof import('~icons/mdi/refresh')['default']
    IconMdiWechat: typeof import('~icons/mdi/wechat')['default']
    IconMdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
    IconPhCaretDoubleLeftBold: typeof import('~icons/ph/caret-double-left-bold')['default']
    IconPhCaretDoubleRightBold: typeof import('~icons/ph/caret-double-right-bold')['default']
    IconSelect: typeof import('./src/components/custom/IconSelect.vue')['default']
    ImageVerify: typeof import('./src/components/custom/ImageVerify.vue')['default']
    LoadingEmptyWrapper: typeof import('./src/components/business/LoadingEmptyWrapper.vue')['default']
    NaiveProvider: typeof import('./src/components/common/NaiveProvider.vue')['default']
    WebSiteLink: typeof import('./src/components/custom/WebSiteLink.vue')['default']
  }
}

export { }
